import {StyleSheet} from 'react-native';

export default StyleSheet.create({
    swiperImg:{
        height:150,
        width:'100%',
    },
    nav:{
        width:"100%",
        height:83.655,
        backgroundColor:'#fff',
        flexDirection:'row',
    },
    navImage:{
        flex:1
    },
    activityNav:{
        width:'100%',
        height:227.775,
        backgroundColor:'#fff',
        flexDirection:'row',
    },
    good:{
        width:'100%',
        height:47.92,
        marginTop:10,
        marginBottom:10,
        backgroundColor:'#fff',
    },
    connectNav:{
        width:'100%',
        height:44,
        backgroundColor:'#fff',
        flexDirection:'row'
        
    },
    navViewCommon:{
        width:84,
        height:'100%',
        marginHorizontal:10,
    },
    navViewActivity:{
        width:84,
        height:'100%',
        marginHorizontal:10,
        borderStyle:'solid',
        borderBottomColor:'#ff464e',
        borderBottomWidth: 2 ,
    },
    navTextCommon:{
        color:'#333',
        fontSize:16,
        lineHeight:44,
        textAlign:'center'
    },
    navTextActivity:{
        color:'#ff464e',
        fontSize:16,
        lineHeight:44,
        textAlign:'center'
    }
})